PORT = 80
HOST = "0.0.0.0"
ADMIN_PASSWORD = "20010519"
DJ_PASSWORD = "dj_password"
DEBUG = not True
MAX_ORDER_TIME_PER_DAY = 1
SALT = "CCCCTTTTQQQQLLLL"
# mysql://用户名:密码@主机/数据库名
USE_DATABASE = False
SQL_CONNECT = ""
USING_SSL = True
